### PR TITLE
Support for PrismJS

### PR DESCRIPTION
**Pull request by jawache**
Ok got it working, please can you take a look @osamajandali let me know if I did this right? :)

Related to issue #17

### CODE REVIEW

**Comment by osamajandali** [comment]
I think we just need to add the branding theme but other than that prefect..
image

**Comment by jawache** [comment]
Thanks @osamajandali - sorry I don't understand :/ what do you mean by the "branding theme"?

**Comment by osamajandali** [comment]
@jawache I meant brand theme sry 😄 .. the background should be like the photo dark blue and the syntax highlighting should be somehow related to logo blue and yellow

**Comment by jawache** [comment]
@osamajandali gotcha! Hmmm i've changed the background to be the same as the brand, but i've left the syntax highlighting alone for now - it get's "complex" :)

**Pull request merged**
